[package]
name = "echoscrape"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
regex = "1.11.2" 
reqwest = { version =  "0.12.23", features = ["blocking"] }
serde = "1.0.219"
tl = "0.7.8"
